# Generated by Django 4.2.7 on 2024-01-07 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_category_alter_auction_price_alter_bids_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
